spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/trading_db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # create, update, none 등 선택 가능
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # 기본 로그 레벨 설정 (선택)
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
